[package]
name = "my_first_package"
version = "0.0.1"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
# Sui = { git = "https://gitclone.com/github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
Sui = { local = "../../Sui/crates/sui-framework" }

[addresses]
try_fungible_token =  "0x0"
abc = "0x0"
rc = "0x0"
sui =  "0000000000000000000000000000000000000002"
